### ISSUE TITLE
Refactor onprem CDS Dashboards code to use new useroptions branch

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub-onprem#45]
There is a branch in the cdsdashboards repo incorporating 'spawner options' into the core dashboard build process. This should allow you to simplify your code, and fixes the problem with restarting the server breaking the dashboard-ness of it (launching JupyterLab instead).

https://github.com/ideonate/cdsdashboards/tree/useroptions

I'm very happy to do this refactoring, but assigned to Adam so he can assign back to me if he doesn't prefer to do it himself, or add any notes etc.

**Comment by Adam-D-Lewis** [comment]
@danlester Can you walk me through the relevant changes sometime?  It'll help me work with the new changes more quickly.

**Comment by Adam-D-Lewis** [comment]
Here's the error I'm currently seeing when I click the save button on the dashboardedit page, then click on the save button on the instance resources page.
```python
Mar 05 20:46:14 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:14.210 JupyterHub log:181] 200 GET /hub/dashboards (example-user@::ffff:192.168.121.1) 29.52ms
Mar 05 20:46:14 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:14.309 JupyterHub log:181] 302 GET /dashboards-static/css/style.css -> /hub/dashboards-static/css/style.css (@::ffff:192.168.
Mar 05 20:46:14 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:14.351 JupyterHub log:181] 302 GET /logo -> /hub/logo (@::ffff:192.168.121.1) 2.15ms
Mar 05 20:46:16 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:16.370 JupyterHub log:181] 200 GET /hub/dashboards/panel12481/edit (example-user@::ffff:192.168.121.1) 26.23ms
Mar 05 20:46:16 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:16.470 JupyterHub log:181] 302 GET /dashboards-static/css/style.css -> /hub/dashboards-static/css/style.css (@::ffff:192.168.
Mar 05 20:46:16 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:16.514 JupyterHub log:181] 302 GET /logo -> /hub/logo (@::ffff:192.168.121.1) 0.91ms
Mar 05 20:46:21 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:21.226 JupyterHub log:181] 302 POST /hub/dashboards/panel12481/edit -> /hub/dashboards/panel12481 (example-user@::ffff:192.16
Mar 05 20:46:21 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:21.227 JupyterHub processbuilder:18] Starting Builder start function
Mar 05 20:46:21 hpc01-test jupyterhub[1193]: [W 2021-03-05 20:46:21.228 JupyterHub configurable:190] Config option `options_from_form` not recognized by `QHubHPCSpawner`.  Did you mean `opti
Mar 05 20:46:21 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:21.229 JupyterHub processbuilder:50] Options form is present
Mar 05 20:46:21 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:21.292 JupyterHub log:181] 302 GET /hub/dashboards/panel12481 -> /hub/dashboards/panel12481/options (example-user@::ffff:192.
Mar 05 20:46:21 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:21.393 JupyterHub main:436] Display options form
Mar 05 20:46:21 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:21.400 JupyterHub log:181] 200 GET /hub/dashboards/panel12481/options (example-user@::ffff:192.168.121.1) 10.88ms
Mar 05 20:46:21 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:21.529 JupyterHub log:181] 302 GET /dashboards-static/css/style.css -> /hub/dashboards-static/css/style.css (@::ffff:192.168.
Mar 05 20:46:21 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:21.532 JupyterHub log:181] 302 GET /logo -> /hub/logo (@::ffff:192.168.121.1) 0.89ms
Mar 05 20:46:26 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:26.155 JupyterHub log:181] 200 GET /hub/metrics (prometheus@::ffff:127.0.0.1) 33.16ms
Mar 05 20:46:32 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:32.003 JupyterHub log:181] 302 POST /hub/dashboards/panel12481/options -> /hub/dashboards/panel12481 (example-user@::ffff:192
Mar 05 20:46:32 hpc01-test jupyterhub[1193]: [I 2021-03-05 20:46:32.003 JupyterHub processbuilder:18] Starting Builder start function
Mar 05 20:46:32 hpc01-test jupyterhub[1193]: [E 2021-03-05 20:46:32.003 JupyterHub processbuilder:59] Failed to spawn dashboard server with form
Mar 05 20:46:32 hpc01-test jupyterhub[1193]:     Traceback (most recent call last):
Mar 05 20:46:32 hpc01-test jupyterhub[1193]:       File "/opt/conda/envs/jupyterhub/lib/python3.9/site-packages/cdsdashboards/builder/processbuilder.py", line 56, in start
Mar 05 20:46:32 hpc01-test jupyterhub[1193]:         user_options = await maybe_future(spawner.options_from_form(form_options))
Mar 05 20:46:32 hpc01-test jupyterhub[1193]:       File "/opt/conda/envs/jupyterhub/lib/python3.9/site-packages/cdsdashboards/hubextension/spawners/variablemixin.py", line 310, in options_fr
Mar 05 20:46:32 hpc01-test jupyterhub[1193]:         formdata = super().options_from_form(options)
Mar 05 20:46:32 hpc01-test jupyterhub[1193]:       File "/opt/conda/envs/jupyterhub/lib/python3.9/site-packages/traitlets/traitlets.py", line 575, in __get__
Mar 05 20:46:32 hpc01-test jupyterhub[1193]:         return self.get(obj, cls)
Mar 05 20:46:32 hpc01-test jupyterhub[1193]:       File "/opt/conda/envs/jupyterhub/lib/python3.9/site-packages/traitlets/traitlets.py", line 538, in get
Mar 05 20:46:32 hpc01-test jupyterhub[1193]:         default = obj.trait_defaults(self.name)
Mar 05 20:46:32 hpc01-test jupyterhub[1193]:       File "/opt/conda/envs/jupyterhub/lib/python3.9/site-packages/traitlets/traitlets.py", line 1574, in trait_defaults
Mar 05 20:46:32 hpc01-test jupyterhub[1193]:         raise TraitError("'%s' is not a trait of '%s' "
Mar 05 20:46:32 hpc01-test jupyterhub[1193]:     traitlets.traitlets.TraitError: 'options_from_form' is not a trait of 'QHubHPCSpawner' instances

```
